version: '3.8'
services:
  db:
    image: postgres:16
    container_name: for-pgroll
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5440:5432"
